In [1]:
message = "Hello, World!"
println(message)

Hello, World!


In [2]:
typeof(message)

String

In [3]:
# Single-line comment

#=

Multi-line comment

=#

In [4]:
power = 10 ^ 2
power

100

In [5]:
typeof('a') # It's not possible to define a string using `''` 

Char

## Strings

In [6]:
# String interpolation

str = "String"
value_1 = 1
value_2 = 2

println("$str interpolation!")
println("$(value_1 + value_2)")

String interpolation!
3


In [7]:
# String concatenation

hello = "Hello"
world = "World"

println(string(hello, ", ", world, "!"))
println(hello*world)
println("$hello$world")

Hello, World!
HelloWorld
HelloWorld


## Dictionaries

In [8]:
d = Dict("key" => "value") # Dictionaries are not ordered
d["new_key"] = "new_value"
d

Dict{String,String} with 2 entries:
  "key"     => "value"
  "new_key" => "new_value"

In [9]:
d["key"]

"value"

In [10]:
pop!(d, "new_key")

"new_value"

In [11]:
d

Dict{String,String} with 1 entry:
  "key" => "value"

## Tuples

In [12]:
t = (1, 2, 3) # Tuples are ordered and immutable
t

(1, 2, 3)

In [13]:
t[1] # 1-based indexing

1

## Arrays

In [14]:
a = [1, 2, 3] # Arrays are ordered and mutable
a

3-element Array{Int64,1}:
 1
 2
 3

In [15]:
a[2]

2

In [16]:
a[1] = 10
a

3-element Array{Int64,1}:
 10
  2
  3

In [17]:
push!(a, 25) # Adds an element to the end of an array
a

4-element Array{Int64,1}:
 10
  2
  3
 25

In [18]:
pop!(a) # Removes the last element of an array
a

3-element Array{Int64,1}:
 10
  2
  3

In [19]:
aa = [[1, 2, 3], [4, 5, 6]]
aa

2-element Array{Array{Int64,1},1}:
 [1, 2, 3]
 [4, 5, 6]

In [20]:
rand(4, 3) # Random values between 0 and 1

4×3 Array{Float64,2}:
 0.0215868  0.0550508  0.256133
 0.407405   0.840786   0.980205
 0.996025   0.237666   0.199854
 0.91072    0.0315215  0.849647

In [21]:
rand(4, 3, 1)

4×3×1 Array{Float64,3}:
[:, :, 1] =
 0.870336   0.389438   0.577144
 0.658853   0.341136   0.566008
 0.0649969  0.0626078  0.167452
 0.487986   0.296057   0.381458

## Loops

In [22]:
n = 0
while n < 10
  n += 1
  println(n)
end

1
2
3
4
5
6
7
8
9
10


In [23]:
println("`in`")
for n in 1:5 # Inclusive
  println(n)
end

println("`=`")
for n = 1:5
  println(n)
end

println("`∈`")
for n ∈ 1:5
  println(n)
end

`in`
1
2
3
4
5
`=`
1
2
3
4
5
`∈`
1
2
3
4
5


In [24]:
m, n = 5, 5
A = zeros(m, n)

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [25]:
for i in 1:m
  for j in 1:n
    A[i, j] = i + j
  end
end

A

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [26]:
# Nested `for` loop

B = zeros(m, n)

for i in 1:m, j in 1:n
  B[i, j] = i + j
end

B

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [27]:
# The more "Julia" way is with an array comprehension

C = [i + j for i in 1:m, j in 1:n]
C

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

## Conditionals